version: '3'
services:
  minnemi-backend:

    image: m1nnemi/back:latest
    environment:
      - API_ENV=production
    volumes:
      - .:/var/www/html

    command: composer production-deps-permissions-start-app

networks:
  stack_network:
