version: '3'
services:
  minnemi-backend:

    image: m1nnemi/back:latest
    environment:
      - API_ENV=production
    volumes:
      - .:/var/www/html

    command: /bin/bash -c "sh /var/www/html/scripts/api.sh"

networks:
  stack_network:
