version: '3'

services:
  api:
    container_name: api
    build: .
    environment:
      - COMPOSER_PROCESS_TIMEOUT=600
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - stack_network
    command: composer development-deps-permissions-start-app

  mysql:
    container_name: main_data
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - stack_network

networks:
  stack_network:

volumes:
  mysql_data:
