version: '3'

services:
  minnemi-backend:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - stack_network
    command: composer production-deps-permissions-start-app

networks:
  stack_network:
