name: CI/CD Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  URL: ${{ secrets.API_URL }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sleep for 6 seconds
        run: sleep 6s

      - name: Make Script Executable
        run: chmod u+x index.sh

      - name: Execute Script
        run: ./index.sh
