name: CI DE DEPLOY

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - 
      uses: actions/checkout@v3 
    - 
      name: Sleep for 6 seconds
      run: sleep 6s
      shell: bash 
    - 
      name: Executar Script
      run: |
        chmod u+x index.sh
        ./index.sh
      
