name: CI/CD Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sleep for 6 seconds
        run: sleep 6s

      - name: Execute Script
        run: | 
          chmod u+x index.sh
          ./index.sh

        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
