name: CI DE DEPLOY

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - 
      uses: actions/checkout@v3 
    
    - 
      name: Set up environment
      run: |
        URL=$API_URL
        API_KEY=$API_KEY
    - 
      name: Executar Script
      run: |
        chmod u+x index.sh
        ./index.sh
      
